version: 1
disable_existing_loggers: false

formatters:
  verbose:
    format: '%(levelname)s %(asctime)s %(module)s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: verbose

loggers:
  path_tmpl_worker:
    level: DEBUG
    handlers: [console]
  celery:
    level: INFO
    handlers: [ console ]