[tool.poetry]
name = "path-tmpl-worker"
version = "0.1.0"
description = "Path template worker"
authors = ["Eugen Ciur <eugen@papermerge.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
jinja2 = "^3.1.4"
sqlalchemy = "^2.0.36"
pydantic-settings = "^2.6.0"
pydantic = "^2.9.2"
typer = "^0.12.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[tool.poetry.scripts]
move_document = 'path_tmpl_worker.cli.main:app'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
